version: "3.8"

services:
     devry-services:
          environment:
               TZ: "America/New_York"
          image: "mercenary9312/unofficial-devry-service-bot"
          restart: "always"
          volumes:
            - ${PWD}/DevryCommunity.db:/app/DevryCommunity.db
            - ${PWD}/Configs:/app/Configs
            - ${PWD}/Snippets:/app/Snippets