name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
    - name: Add DSharpPlus Nuget Source
      run: dotnet nuget add source https://nuget.emzi0767.com/api/v3/index.json --name DSharpPlus
    - name: Restore dependencies
      run: dotnet restore DevryService
    - name: Build
      run: dotnet build --no-restore --configuration Release --no-restore
    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Create File
      id: write_file
      uses: timheuer/base64-to-file@v1
      with:
        filename: 'token.txt'
        encodedString: ${{ secrets.DISCORD_TOKEN }}        
    - name: Build Docker Image
      env:
        TOKEN: $(cat ${{ steps.write_file.outputs.filePath }})  
      run: docker build --build-arg TOKEN=$TOKEN -f DevryService/Dockerfile -t mercenary9312/unofficial-devry-service-bot .
    - name: Push Docker Image
      run: docker push mercenary9312/unofficial-devry-service-bot
          
