name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
    - name: Restore dependencies
      run: dotnet restore DevryService
    - name: Build
      run: dotnet build --no-restore --configuration Release --no-restore
    - name: Docker Build
      run: docker build -f DevryService/Dockerfile -t mercenary9312/unofficial-devry-service-bot .
    - name: Push Docker
      run: docker push mercenary9312/unofficial-devry-service-bot
          
