name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
    - name: Add DSharpPlus Nuget Source
      run: dotnet nuget add source https://nuget.emzi0767.com/api/v3/index.json --name DSharpPlus
    - name: Restore dependencies
      run: dotnet restore DevryService
    - name: Build
      run: dotnet build --no-restore --configuration Release --no-restore
    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}    
    - name: Build Docker Image
      run: docker build -f DevryService/Dockerfile -t mercenary9312/unofficial-devry-service-bot .
    - name: Push Docker Image
      run: docker push mercenary9312/unofficial-devry-service-bot
          
