version: "3.8"

services:
  devry-services:
    environment:
      TZ: "America/New_York"
    image: "mercenary9312/unofficial-devry-service"
    depends_on: 
      - devry-services-db
    restart: "always"

  devry-services-db:
    environment:
      TZ: "America/New_York"
    image: "mercenary9312/unofficial-devry-service-db"
    volumes:
      - ${PWD}/data:/var/lib/mysql
    restart: "always"
    